### ISSUE TITLE
Required detailed information about classes-header.jar

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [JetpackDuba/android-jar-with-hidden-api#2]
In readme.md you wrote,what in aosp folder we can find class classes-header.jar. But when i can find this folder. Please give more information in readme or generate .jar for android 11,12 and 13.

**Comment by JetpackDuba** [comment]
You need to clone and build [AOSP](https://source.android.com/docs/setup/download/downloading). I don't have an AOSP build available right now nor enough storage to do it myself.

**Comment by AlexandrKozlovskiy** [comment]
@JetpackDuba Should i install repo launcher for this,or i can avoid it?

**Comment by JetpackDuba** [comment]
Yes, you need repo & a linux based distro. More info here:

https://source.android.com/docs/setup/start/requirements


https://source.android.com/docs/setup/start/initializing

Note that you need a powerful machine to build AOSP.

**Comment by AlexandrKozlovskiy** [comment]
@JetpackDuba But i have windows 11.

**Comment by JetpackDuba** [comment]
Linux is a must for AOSP, sorry. You may have luck building with a VM but take in considerarion that a build can take from 80 to 200GB of storage and a few hours to compile
